name: esy CI

on:
  pull_request:
  push:
   branches:
     - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        ocaml-compiler:
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install esy
        run: npm install -g --prefer-offline --audit false esy@0.6.12

      - name: Debug
        shell: bash
        run: echo $GITHUB_PATH;

      - name: Check esy version
        run: esy --version
