name: esy CI

on:
  pull_request:
  push:
   branches:
     - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        ocaml-compiler:
          - 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install esy
        run: npm install --prefer-offline --audit false

      - name: Expose esy as binary
        if: runner.os == 'Windows'
        run: |
          ls node_modules;
          echo "---------------------------";
          nodeInstallPath=$(npm config get prefix)
          ls $nodeInstallPath\bin;
          echo "$nodeInstallPath\bin" >> $GITHUB_PATH

      - name: Expose esy as binary
        if: runner.os != 'Windows'
        run: |
          nodeInstallPath=$(npm config get prefix)
          ls $nodeInstallPath/bin;
          echo "$nodeInstallPath/bin" >> $GITHUB_PATH

      # - name: Expose esy as binary
        # run: |
          # mkdir ~/.npm-global
          # npm config set prefix '~/.npm-global'
          # export PATH=~/.npm-global/bin:$PATH
          # nodeInstallPath=$(npm config get prefix)
          # echo "$nodeInstallPath/bin" >> $GITHUB_PATH

      - name: Debug
        shell: bash
        run: echo $GITHUB_PATH;

      - name: Check esy version
        run: esy --version
